language: java
install:
  - "sudo apt-get install javacc dosemu"
script:
  - "make"
  - "make test"
  - "./travis/configure-layout.sh"
  - "make download-tasm"
  - "make package"
  - "make run-asm FILE=example/function.yaka"
  - "make run-asm FILE=example/factorielle.yaka"
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7

matrix:
  allow_failures:
    - jdk: oraclejdk7
    - jdk: openjdk7
  fast_finish: true

notifications:
  email: false
