language: java
install:
  - "sudo apt-get install javacc dosemu"
script:
  - "make javacc"
  - "make test"
  - "sudo echo '$_layout = \"uk\"' >> /etc/dosemu/dosemu.conf"
  - "make download-tasm"
  - "make test-asm"
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7

matrix:
  allow_failures:
    - jdk: oraclejdk7
    - jdk: openjdk7
  fast_finish: true

notifications:
  email: false
